#!/usr/bin/env node

console.log('🚂 Railway Deployment Guide for Your Portfolio\n');

console.log('📋 Quick Setup Steps:\n');

console.log('1️⃣ **Deploy Backend to Railway**');
console.log('   🔧 If repositories not loading, try these options:');
console.log('   ');
console.log('   Option A: GitHub Integration Issues');
console.log('   • Go to https://railway.app');
console.log('   • Click your profile → Settings → Connections');
console.log('   • Reconnect GitHub integration');
console.log('   • Grant access to your repositories');
console.log('   ');
console.log('   Option B: Direct Repository Link');
console.log('   • Go to https://railway.app/new');
console.log('   • Paste: https://github.com/Anita-Boke/My-Portfolio');
console.log('   • Click "Deploy from GitHub repo"');
console.log('   ');
console.log('   Option C: Railway CLI');
console.log('   • npm install -g @railway/cli');
console.log('   • railway login');
console.log('   • railway link');
console.log('   ');
console.log('   • Add MySQL database service after deployment\n');

console.log('2️⃣ **Environment Variables on Railway**');
console.log('   Add these in Railway dashboard:');
console.log('   EMAIL_USER=wintahboke@gmail.com');
console.log('   EMAIL_PASS=suoj rfnf lvhp basn');
console.log('   ADMIN_EMAIL=wintahboke@gmail.com\n');
console.log('   (DATABASE_URL will be auto-generated by Railway)\n');

console.log('3️⃣ **Update Frontend (Vercel)**');
console.log('   Add Railway backend URL to Vercel:');
console.log('   vercel env add RAILWAY_URL production');
console.log('   # Enter your Railway app URL\n');

console.log('4️⃣ **Benefits of This Setup**');
console.log('   ✅ Frontend: Fast static hosting on Vercel');
console.log('   ✅ Backend: Reliable Node.js + MySQL on Railway');
console.log('   ✅ Email: No SMTP blocking issues');
console.log('   ✅ Database: Managed MySQL with auto-backups');
console.log('   ✅ Scaling: Both platforms auto-scale\n');

console.log('🎉 Your portfolio will be production-ready!\n');

console.log('📖 More details in RAILWAY_SETUP.md');

// Open Railway
console.log('🌐 Opening Railway...');
const { execSync } = require('child_process');
try {
  execSync('start https://railway.app', { stdio: 'ignore' });
} catch (error) {
  console.log('   Please visit: https://railway.app');
}